root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/app main.go"
bin = "tmp/app"
full_bin = "./tmp/app"
include_ext = ["go", "html", "json", "txt", "toml"]
exclude_dir = ["assets", "tmp", "vendor", ".git"]
exclude_file = []
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
follow_symlink = true
delay = 500
stop_on_error = true
send_interrupt = false
kill_delay = 500

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
